package modules

import (
	"errors"
	"fmt"
	"goroku/goroku"
	"goroku/goroku/inline"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"
)

func closeForm(call inline.CallbackQuery) error {
	if call.InlineMessage != nil {
		_, err := call.InlineMessage.Delete()
		return err
	}
	if call.BotMessage != nil {
		_, err := call.BotMessage.Delete()
		return err
	}
	return nil
}

func camelToSnake(s string) string {
	var res strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			res.WriteRune('_')
		}
		res.WriteRune(r)
	}
	return strings.ToLower(res.String())
}

// getTrans fetches a translated string from the translator or returns the default value.
func getTrans(t *goroku.Translator, modName, key, def string) string {
	if t == nil {
		return def
	}

	namesToTry := []string{modName, strings.ToLower(modName), camelToSnake(modName)}
	if strings.EqualFold(modName, "APILimiter") {
		namesToTry = append(namesToTry, "api_protection")
	}
	if strings.EqualFold(modName, "Tester") {
		namesToTry = append(namesToTry, "test")
	}

	for _, name := range namesToTry {
		searchKey := fmt.Sprintf("goroku.modules.%s.%s", name, key)
		if val := t.GetKey(searchKey); val != nil {
			return fmt.Sprintf("%v", val)
		}
	}
	return def
}

func RegisterModulesAndRebuild(msg *goroku.Message, structNames []string) error {
	if msg != nil && msg.Client != nil {
		return RegisterModulesHot(msg, structNames)
	}
	return fmt.Errorf("client is required for hot module loading")
}

func runtimeModuleSourceDir() string {
	return filepath.Join(goroku.BaseDir, "modules")
}

func legacyModuleSourceDir() string {
	return filepath.Join(goroku.BasePath, "goroku", "modules")
}

func runtimeModuleSourcePath(moduleName string) (string, error) {
	if moduleName == "" || filepath.Base(moduleName) != moduleName || strings.ContainsAny(moduleName, `/\`) {
		return "", fmt.Errorf("invalid module name %q", moduleName)
	}
	return filepath.Join(runtimeModuleSourceDir(), moduleName+".go"), nil
}

// runtimeModuleGoMod marks the runtime module directory as its own Go module.
//
// The directory holds sources the user installed at runtime (.dlmod/.loadmod/
// presets) and is gitignored. Without this marker it sits inside the main
// module as package goroku/modules, so `go build ./...`, `go vet ./...` and
// golangci-lint compile and lint third-party code along with the product: one
// bad installed module breaks the build, and CI (which clones without the
// directory) checks a different package set than local development.
const runtimeModuleGoMod = `// Nested module: keeps runtime-installed sources out of the main module's
// package graph. Generated by Goroku; not part of the product build or CI.
module goroku_runtime_modules

go 1.24.4
`

func ensureRuntimeModuleSourceDir() error {
	dir := runtimeModuleSourceDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}
	// Written once; never overwritten, so a user who edits it keeps their version.
	goModPath := filepath.Join(dir, "go.mod")
	if _, err := os.Stat(goModPath); err == nil {
		return nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	// 0644, unlike the module sources beside it: the Go tool has to read this
	// marker to know the directory is a nested module and skip the sources.
	if err := os.WriteFile(goModPath, []byte(runtimeModuleGoMod), 0644); err != nil { //nolint:gosec
		return fmt.Errorf("mark runtime module directory as a nested module: %w", err)
	}
	return nil
}

func findInstalledModuleSource(moduleName string) (string, error) {
	runtimePath, err := runtimeModuleSourcePath(moduleName)
	if err != nil {
		return "", err
	}
	if info, err := os.Stat(runtimePath); err == nil && !info.IsDir() {
		return runtimePath, nil
	}
	return "", fmt.Errorf("source for module %s not found", moduleName)
}

func findModuleSource(structName string) (string, error) {
	if preferred, err := findInstalledModuleSource(structName); err == nil {
		return preferred, nil
	}

	files, err := filepath.Glob(filepath.Join(runtimeModuleSourceDir(), "*.go"))
	if err != nil {
		return "", err
	}
	for _, file := range files {
		content, err := os.ReadFile(file) //nolint:gosec
		if err != nil {
			continue
		}
		if moduleSourceDeclaresStruct(content, structName) {
			return file, nil
		}
	}

	return "", fmt.Errorf("source for module struct %s not found", structName)
}

// findRegisteredModuleSource resolves a local module by its Go struct name,
// which may differ from the user-facing name returned by Name().
func findRegisteredModuleSource(module goroku.Module) (string, error) {
	name := registeredModuleStructName(module)
	if name == "" {
		return "", fmt.Errorf("invalid module type")
	}
	return findModuleSource(name)
}

// findModuleSourceForExport also searches the statically compiled module
// package. It is deliberately separate from findRegisteredModuleSource so a
// built-in module is never mistaken for an unloadable runtime module.
func findModuleSourceForExport(module goroku.Module) (string, error) {
	if path, err := findRegisteredModuleSource(module); err == nil {
		return path, nil
	}
	name := registeredModuleStructName(module)
	if name == "" {
		return "", fmt.Errorf("invalid module type")
	}
	files, err := filepath.Glob(filepath.Join(legacyModuleSourceDir(), "*.go"))
	if err != nil {
		return "", err
	}
	for _, file := range files {
		content, err := os.ReadFile(file) //nolint:gosec
		if err == nil && moduleSourceDeclaresStruct(content, name) {
			return file, nil
		}
	}
	return "", fmt.Errorf("source for module struct %s not found", name)
}

func registeredModuleStructName(module goroku.Module) string {
	moduleType := reflect.TypeOf(module)
	for moduleType != nil && moduleType.Kind() == reflect.Pointer {
		moduleType = moduleType.Elem()
	}
	if moduleType == nil || moduleType.Name() == "" {
		return ""
	}
	return moduleType.Name()
}

func formatTrans(trans string, args ...string) string {
	res := trans
	res = strings.ReplaceAll(res, "href={}", "href=\"{}\"")
	res = strings.ReplaceAll(res, "href='{}'", "href=\"{}\"")
	reEmoji := regexp.MustCompile(`emoji-id=([0-9]+)`)
	res = reEmoji.ReplaceAllString(res, `emoji-id="$1"`)

	for i, arg := range args {
		res = strings.ReplaceAll(res, fmt.Sprintf("{%d}", i), arg)
	}
	for _, arg := range args {
		res = strings.Replace(res, "{}", arg, 1)
	}
	return res
}
